sonar.projectKey=jahnavi-api
sonar.projectName=Jahnavi API
sonar.projectVersion=1.0.0

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/config/**,**/dto/**,**/model/**,**/exception/**,**/ApiApplication.java
sonar.test.exclusions=**/test/**

sonar.java.source=17
sonar.sourceEncoding=UTF-8

sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S6813
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.java
