spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/jahnavidb}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  h2:
    console:
      enabled: false

springdoc:
  swagger-ui:
    enabled: false

logging:
  level:
    com.jahnavi.api: WARN
